{
 "title": "Fortinet Firewall SNMP Dashboard for Prometheus Copy",
 "description": "飞塔防火墙监控仪表盘",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "sysname", "label": "选择设备", "query": { "query": "label_values(gwname)" } },
   {
    "name": "interface",
    "label": "接口",
    "query": {
     "query": "query_result(count by (ifName) (count_over_time(ifHCInOctets[$__range])))"
    }
   },
   { "name": "vdom", "label": "vdom", "query": { "query": "label_values(fgVdEntName)" } }
  ]
 },
 "panels": [
  {
   "title": "设备基本信息",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sysName{gwname=~\"$sysname\"} - 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "fnSysSerial{gwname=~\"$sysname\"} - 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "fgSysUpTime{gwname=~\"$sysname\"} / 100 / 86400 - 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(gwname) (rate(ifHCOutOctets{gwname=~\"$sysname\"}[5m]) * 8) - 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(gwname) (rate(ifHCInOctets{gwname=~\"$sysname\"}[5m]) * 8) - 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "fortigage Internet",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(ifHCOutOctets{gwname=~\"$sysname\",ifName=~\"(?i)^wan1\\\\..*\"}[5m]) * 8",
     "legendFormat": "{{gwname}}-{{ifName}}-TX"
    },
    {
     "expr": "- rate(ifHCInOctets{gwname=~\"$sysname\",ifName=~\"(?i)^wan1\\\\..*\"}[5m]) * 8",
     "legendFormat": "{{gwname}}-{{ifName}}-RX"
    }
   ]
  },
  {
   "title": "fortigate mpls backbone",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "rate(ifHCOutOctets{gwname=~\"$sysname\",ifName=~\"(?i)^internal1\\\\..*\"}[5m]) * 8 ",
     "legendFormat": "{{gwname}}-{{ifName}}-TX"
    },
    {
     "expr": "- rate(ifHCInOctets{gwname=~\"$sysname\",ifName=~\"(?i)^internal1\\\\..*\"}[5m]) * 8 ",
     "legendFormat": "{{gwname}}-{{ifName}}-RX"
    }
   ]
  },
  {
   "title": "CPU使用率",
   "type": "timeseries",
   "description": "该设备实例总CPU使用率",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "fgSysCpuUsage{gwname=~\"$sysname\"}",
     "legendFormat": "{{gwname}}"
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "timeseries",
   "description": "该设备实例总内存使用率",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "fgSysMemUsage{gwname=~\"$sysname\"}",
     "legendFormat": "{{gwname}}"
    }
   ]
  },
  {
   "title": "磁盘使用率",
   "type": "timeseries",
   "description": "磁盘使用率",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(fgSysDiskUsage{gwname=~\"$sysname\"} / fgSysDiskCapacity{gwname=~\"$sysname\"}) * 100 unless fgSysDiskCapacity{gwname=~\"$sysname\"} == 0",
     "legendFormat": "{{gwname}}"
    }
   ]
  },
  {
   "title": "系统并发会话数（个）",
   "type": "timeseries",
   "description": "该设备实例当前系统并发连接数",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "fgSysSesCount{gwname=~\"$sysname\"}",
     "legendFormat": "{{gwname}}"
    }
   ]
  },
  {
   "title": "ipsec Tunnel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "Kibits" } },
   "targets": [
    {
     "expr": "- rate(fgVpnTunEntInOctets{fgVdEntName=~\"$vdom\", gwname=~\"$sysname\"}[5m]) * 8 / 1000",
     "legendFormat": "{{gwname}}-{{fgVdEntName}}-{{fgVpnTunEntPhase1Name}}-RX"
    },
    {
     "expr": "rate(fgVpnTunEntOutOctets{fgVdEntName=~\"$vdom\", gwname=~\"$sysname\"}[5m]) * 8 / 1000",
     "legendFormat": "{{gwname}}-{{fgVdEntName}}-{{fgVpnTunEntPhase1Name}}-TX"
    }
   ]
  },
  {
   "title": "指定接口：{$interface} 出站/入站",
   "type": "timeseries",
   "description": "该设备接口出入接口流量速率",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(ifHCOutOctets{gwname=~\"$sysname\", ifName=~\"$interface\"}[5m]) * 8",
     "legendFormat": "上行: {{ifName}} ({{ifAlias}})"
    },
    {
     "expr": "- rate(ifHCInOctets{gwname=~\"$sysname\", ifName=~\"$interface\"}[5m]) * 8",
     "legendFormat": "下行: {{ifName}} ({{ifAlias}})"
    }
   ]
  },
  {
   "title": "当前接口出站 - Top 10",
   "type": "bargauge",
   "description": "当前接口出站流量速率前十",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "topk(10, rate(ifHCOutOctets{ifName=~\"(?i)^wan1\\\\..*\"}[5m]) * 8)",
     "legendFormat": "{{gwname}}-{{ifName}}"
    }
   ]
  },
  {
   "title": "当前接口入站 - Top 10",
   "type": "bargauge",
   "description": "当前接口入站流量速率前十",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "topk(10, rate(ifHCInOctets{ifName=~\"(?i)^wan1\\\\..*\"}[5m]) * 8)",
     "legendFormat": "{{gwname}}-{{ifName}}"
    }
   ]
  },
  {
   "title": "当前接口出站 - Top 10",
   "type": "bargauge",
   "description": "当前接口出站流量速率前十",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "topk(10, rate(ifHCOutOctets{gwname=~\"$sysname\",ifName=~\"(?i)^internal1\\\\..*\"}[5m]) * 8)",
     "legendFormat": "{{gwname}}-{{ifName}}"
    }
   ]
  },
  {
   "title": "当前接口入站 - Top 10",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "topk(10, rate(ifHCInOctets{gwname=~\"$sysname\",ifName=~\"(?i)^internal1\\\\..*\"}[5m]) * 8)",
     "legendFormat": "{{gwname}}-{{ifName}}"
    }
   ]
  },
  { "title": "防火墙 IPSec VPN 信息", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "IPSec VPN",
   "type": "table",
   "description": "设备中IPSec VPN的对接信息",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "fgVpnTunEntRemGwyIp{gwname=~\"$sysname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "fgVpnTunEntLocGwyIp{gwname=~\"$sysname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "fgVpnTunEntLifeSecs{gwname=~\"$sysname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "fgVpnTunEntTimeout{gwname=~\"$sysname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "fgVpnTunEntInOctets{gwname=~\"$sysname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "fgVpnTunEntOutOctets{gwname=~\"$sysname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "fgVpnTunEntStatus{gwname=~\"$sysname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "fgVpnTunEntVdom{gwname=~\"$sysname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "防火墙健康检查信息", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "SD-WAN 健康检查",
   "type": "table",
   "description": "SD-WAN 健康检查信息",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 69 },
   "targets": [
    {
     "expr": "fgVWLHealthCheckLinkID{gwname=~\"$sysname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "fgVWLHealthCheckLinkSeq{gwname=~\"$sysname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "fgVWLHealthCheckLinkState{gwname=~\"$sysname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "fgVWLHealthCheckLinkLatency{gwname=~\"$sysname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "fgVWLHealthCheckLinkJitter{gwname=~\"$sysname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "fgVWLHealthCheckLinkPacketSend{gwname=~\"$sysname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "fgVWLHealthCheckLinkPacketRecv{gwname=~\"$sysname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "fgVWLHealthCheckLinkPacketLoss{gwname=~\"$sysname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "fgVWLHealthCheckLinkVdom{gwname=~\"$sysname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "fgVWLHealthCheckLinkUsedBandwidthIn{gwname=~\"$sysname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "fgVWLHealthCheckLinkUsedBandwidthOut{gwname=~\"$sysname\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}